# Generated by Django 4.1.1 on 2022-09-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.section'),
        ),
    ]
