# Generated by Django 4.1.1 on 2022-09-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ManyToManyField(null=True, to='users.section'),
        ),
    ]
