# Generated by Django 4.1.1 on 2022-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_section_profile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.ManyToManyField(blank=True, to='users.section'),
        ),
    ]
