# Generated by Django 4.1.1 on 2022-09-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_section_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section_Profile',
        ),
    ]
