# Generated by Django 4.1.1 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_manage', '0003_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
