# Generated by Django 4.1.1 on 2022-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_manage', '0005_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], default='published', max_length=15),
        ),
    ]
