# Generated by Django 4.1.1 on 2022-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_manage', '0007_answer_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered',
        ),
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
